In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("dagma/df_cristian_dagma.csv")

In [4]:
df.head(20)

,nombre_est,tipo_gas,concentracion,fecha,fuente,estacion_id,latitud,longitud,altitud,municipio
0,base aerea,o3,3.335110,2020-01-01 00:00:00,cristian,8285,3.457128,-76.502303,956.0,santiago de cali
1,compartir,o3,10.260367,2020-01-01 00:00:00,cristian,30110,3.425800,-76.474100,960.0,santiago de cali
2,pance,o3,18.441195,2020-01-01 00:00:00,cristian,8288,3.321400,-76.533300,1100.0,santiago de cali
3,univalle,o3,25.660727,2020-01-01 00:00:00,cristian,8291,3.376800,-76.533600,980.0,santiago de cali
4,univalle,no2,8.725094,2020-01-01 00:00:00,cristian,8291,3.376800,-76.533600,980.0,santiago de cali
5,base aerea,o3,3.727476,2020-01-01 01:00:00,cristian,8285,3.457128,-76.502303,956.0,santiago de cali
6,compartir,o3,10.907771,2020-01-01 01:00:00,cristian,30110,3.425800,-76.474100,960.0,santiago de cali
7,pance,o3,17.067915,2020-01-01 01:00:00,cristian,8288,3.321400,-76.533300,1100.0,santiago de cali
8,univalle,o3,23.365387,2020-01-01 01:00:00,cristian,8291,3.376800,-76.533600,980.0,santiago de cali
9,univalle,no2,11.470491,2020-01-01 01:00:00,cristian,8291,3.376800,-76.533600,980.0,santiago de cali
10,base aerea,o3,3.335110,2020-01-01 02:00:00,cristian,8285,3.457128,-76.502303,956.0,santiago de cali
11,compartir,o3,10.515405,2020-01-01 02:00:00,cristian,30110,3.425800,-76.474100,960.0,santiago de cali
12,pance,o3,17.656464,2020-01-01 02:00:00,cristian,8288,3.321400,-76.533300,1100.0,santiago de cali
13,univalle,o3,20.442261,2020-01-01 02:00:00,cristian,8291,3.376800,-76.533600,980.0,santiago de cali
14,univalle,no2,10.191813,2020-01-01 02:00:00,cristian,8291,3.376800,-76.533600,980.0,santiago de cali
15,base aerea,o3,1.961829,2020-01-01 03:00:00,cristian,8285,3.457128,-76.502303,956.0,santiago de cali
16,compartir,o3,9.259834,2020-01-01 03:00:00,cristian,30110,3.425800,-76.474100,960.0,santiago de cali
17,pance,o3,14.321354,2020-01-01 03:00:00,cristian,8288,3.321400,-76.533300,1100.0,santiago de cali
18,univalle,o3,17.519136,2020-01-01 03:00:00,cristian,8291,3.376800,-76.533600,980.0,santiago de cali
19,univalle,no2,9.082372,2020-01-01 03:00:00,cristian,8291,3.376800,-76.533600,980.0,santiago de cali

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 418220 entries, 0 to 418219
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   nombre_est     418220 non-null  str
 1   tipo_gas       418220 non-null  str
 2   concentracion  418220 non-null  float64
 3   fecha          418220 non-null  str
 4   fuente         418220 non-null  str
 5   estacion_id    418220 non-null  int64
 6   latitud        418220 non-null  float64
 7   longitud       418220 non-null  float64
 8   altitud        418220 non-null  float64
 9   municipio      418220 non-null  str
dtypes: float64(4), int64(1), str(5)
memory usage: 53.3 MB

In [6]:
print(f"Desde: {df['fecha'].min()} hasta {df['fecha'].max()}")

Desde: 2020-01-01 00:00:00 hasta 2025-12-11 23:00:00

In [7]:
columnas_categoricas = ['nombre_est', 'tipo_gas', 'fuente', 'estacion_id', 'municipio']
for col in columnas_categoricas:
    if col in df.columns:
        print(f"\nValores únicos en {col}:")
        print(df[col].unique())

Valores únicos en nombre_est:
<ArrowStringArray>
[           'base aerea',             'compartir',                 'pance',
              'univalle',                'ermita',          'canaveralejo',
 'transitoria - navarro',        'estacion yumbo',                 'flora',
          'era - obrero']
Length: 10, dtype: str

Valores únicos en tipo_gas:
<ArrowStringArray>
['o3', 'no2', 'so2']
Length: 3, dtype: str

Valores únicos en fuente:
<ArrowStringArray>
['cristian', 'cvc', 'dagma']
Length: 3, dtype: str

Valores únicos en estacion_id:
[ 8285 30110  8288  8291 30111 30109 30112  8777  8986 30004]

Valores únicos en municipio:
<ArrowStringArray>
['santiago de cali', 'yumbo']
Length: 2, dtype: str

In [8]:
print("\nValores únicos de Latitud:")
print(df['latitud'].unique())

print("\nValores únicos de Longitud:")
print(df['longitud'].unique())

print("\nValores únicos de Altitud:")
print(df['altitud'].unique())

Valores únicos de Latitud:
[3.457128 3.4258   3.3214   3.3768   3.4533   3.4111   3.395    3.579075
 3.4792   3.4525   3.42826  3.377911 3.457317 3.455514 3.416366 3.304517
 3.488218]

Valores únicos de Longitud:
[-76.502303 -76.4741   -76.5333   -76.5336   -76.5311   -76.5444
 -76.488    -76.489558 -76.5072   -76.5222   -76.466584 -76.533811
 -76.506539 -76.530978 -76.549613 -76.531252 -76.518058]

Valores únicos de Altitud:
[ 956.  960. 1100.  980.  962.  975.  950.  952.  965.  985.  968.  994.
  978.  959.]

In [9]:
df.describe()

,concentracion,estacion_id,latitud,longitud,altitud
count,418220.000000,418220.000000,418220.000000,418220.000000,418220.000000
mean,13.980216,17546.878856,3.432562,-76.514441,975.108056
std,17.744138,10653.639889,0.058952,0.021519,40.204466
min,0.000000,8285.000000,3.304517,-76.549613,950.000000
25%,2.827771,8291.000000,3.395000,-76.533300,956.000000
50%,7.295984,8986.000000,3.452500,-76.522200,962.000000
75%,16.400000,30109.000000,3.457128,-76.502303,975.000000
max,86.771710,30112.000000,3.579075,-76.466584,1100.000000

In [10]:
df['concentracion'].describe().round(2)

count    418220.00
mean         13.98
std          17.74
min           0.00
25%           2.83
50%           7.30
75%          16.40
max          86.77
Name: concentracion, dtype: float64

In [11]:
print(df[['nombre_est', 'estacion_id']].drop_duplicates().reset_index(drop=True))

              nombre_est  estacion_id
0             base aerea         8285
1              compartir        30110
2                  pance         8288
3               univalle         8291
4                 ermita        30111
5           canaveralejo        30109
6  transitoria - navarro        30112
7         estacion yumbo         8777
8                  flora         8986
9           era - obrero        30004

In [12]:
print(df.groupby('nombre_est')['tipo_gas'].unique())

nombre_est
base aerea                    [o3, so2]
canaveralejo                      [so2]
compartir                          [o3]
era - obrero                       [o3]
ermita                            [so2]
estacion yumbo           [no2, o3, so2]
flora                         [so2, o3]
pance                              [o3]
transitoria - navarro         [so2, o3]
univalle                      [o3, no2]
Name: tipo_gas, dtype: object

In [13]:
df_zeros = df[df['concentracion'] == 0]
print(df_zeros.groupby('nombre_est')['concentracion'].count())

nombre_est
base aerea                423
canaveralejo             3239
era - obrero               12
ermita                     20
estacion yumbo           1959
flora                    2646
pance                     877
transitoria - navarro    1124
univalle                  746
Name: concentracion, dtype: int64

In [14]:
df_con_datos = df[df['concentracion'] > 0]
print(df_con_datos.groupby('nombre_est')['concentracion'].count())

nombre_est
base aerea               61533
canaveralejo             36134
compartir                40086
era - obrero             33129
ermita                   41171
estacion yumbo           24069
flora                    53841
pance                    36559
transitoria - navarro    20301
univalle                 60351
Name: concentracion, dtype: int64

In [15]:
print(df.groupby(['nombre_est', 'tipo_gas'])['concentracion'].describe().round(2))

                                  count   mean    std   min    25%    50%  \
nombre_est            tipo_gas
base aerea            o3        35323.0  18.34  18.21  0.00   5.83  10.79
                      so2       26633.0   6.38   3.41  0.00   3.88   5.97
canaveralejo          so2       39373.0   1.75   2.16  0.00   0.26   1.13
compartir             o3        40086.0  26.06  21.78  0.47  10.12  16.30
era - obrero          o3        33141.0  17.54  19.36  0.00   4.06   9.55
ermita                so2       41191.0   4.22   2.93  0.00   2.09   3.40
estacion yumbo        no2        4776.0   9.35   5.92  0.00   4.53   8.80
                      o3        11160.0  12.84  11.64  0.00   3.90   7.90
                      so2       10092.0   6.37   5.95  0.00   1.07   4.92
flora                 o3        30287.0  17.76  21.62  0.00   2.65   6.75
                      so2       26200.0   3.11   3.27  0.00   0.52   2.02
pance                 o3        37436.0  24.31  23.26  0.00   5.94  14.87
transitoria - navarro o3         6404.0  22.68  22.12  0.00   5.59  14.69
                      so2       15021.0   4.41   3.24  0.00   1.89   3.82
univalle              no2       25393.0  13.00   8.27  0.00   6.77  11.83
                      o3        35704.0  23.45  20.02  0.00  10.10  15.89

                                  75%    max
nombre_est            tipo_gas
base aerea            o3        24.86  86.77
                      so2        8.82  22.09
canaveralejo          so2        2.28  14.27
compartir             o3        37.47  86.75
era - obrero          o3        23.35  86.75
ermita                so2        5.66  14.30
estacion yumbo        no2       12.90  26.80
                      o3        19.40  45.40
                      so2        9.86  22.36
flora                 o3        26.94  86.75
                      so2        4.61  14.31
pance                 o3        36.92  86.77
transitoria - navarro o3        31.97  86.77
                      so2        6.52  14.30
univalle              no2       18.05  36.99
                      o3        29.78  86.77

In [16]:
df["fecha"] = pd.to_datetime(df["fecha"])

df_cristian_dagma_2021_2025 = df[
    (df["fecha"].dt.year >= 2021) & (df["fecha"].dt.year <= 2025)
].copy()

In [17]:
df_cristian_dagma_2021_2025["fecha"] = pd.to_datetime(df_cristian_dagma_2021_2025["fecha"])
print(df_cristian_dagma_2021_2025["fecha"].dt.year.value_counts().sort_index())

fecha
2021    54727
2022    81021
2023    89653
2024    86154
2025    67980
Name: count, dtype: int64

In [18]:
df_cristian_dagma_2021_2025.to_csv("df_cristian_dagma_2021_2025.csv", index=False)

In [19]:
print(df_cristian_dagma_2021_2025.groupby(['nombre_est', 'tipo_gas'])['concentracion'].describe().round(2))

                                  count   mean    std   min    25%    50%  \
nombre_est            tipo_gas
base aerea            o3        31809.0  18.11  17.66  0.00   5.91  10.93
                      so2       24882.0   6.54   3.35  0.00   4.11   6.13
canaveralejo          so2       33673.0   1.46   1.81  0.00   0.18   0.97
compartir             o3        35462.0  25.48  21.73  0.47   9.69  15.62
era - obrero          o3        33141.0  17.54  19.36  0.00   4.06   9.55
ermita                so2       36843.0   4.07   2.79  0.00   2.04   3.30
estacion yumbo        no2        4776.0   9.35   5.92  0.00   4.53   8.80
                      o3        11160.0  12.84  11.64  0.00   3.90   7.90
                      so2       10092.0   6.37   5.95  0.00   1.07   4.92
flora                 o3        30287.0  17.76  21.62  0.00   2.65   6.75
                      so2       26200.0   3.11   3.27  0.00   0.52   2.02
pance                 o3        32196.0  23.18  23.47  0.00   5.26  12.48
transitoria - navarro o3         6404.0  22.68  22.12  0.00   5.59  14.69
                      so2       13663.0   4.57   3.19  0.00   2.09   4.03
univalle              no2       18828.0  11.86   7.99  0.00   5.90  10.51
                      o3        30119.0  23.09  19.91  0.00  10.12  15.64

                                  75%    max
nombre_est            tipo_gas
base aerea            o3        24.58  86.77
                      so2        8.95  22.09
canaveralejo          so2        1.96  14.27
compartir             o3        36.71  86.75
era - obrero          o3        23.35  86.75
ermita                so2        5.45  14.30
estacion yumbo        no2       12.90  26.80
                      o3        19.40  45.40
                      so2        9.86  22.36
flora                 o3        26.94  86.75
                      so2        4.61  14.31
pance                 o3        35.94  86.77
transitoria - navarro o3        31.97  86.77
                      so2        6.62  14.30
univalle              no2       16.44  36.97
                      o3        28.88  86.77

In [20]:
df_zeros = df_cristian_dagma_2021_2025[df_cristian_dagma_2021_2025['concentracion'] == 0]
print(df_zeros.groupby('nombre_est')['concentracion'].count())

nombre_est
base aerea                422
canaveralejo             3239
era - obrero               12
ermita                     20
estacion yumbo           1959
flora                    2646
pance                     877
transitoria - navarro     808
univalle                  732
Name: concentracion, dtype: int64

In [21]:
df_con_datos = df_cristian_dagma_2021_2025[df_cristian_dagma_2021_2025['concentracion'] > 0]
print(df_con_datos.groupby('nombre_est')['concentracion'].count())

nombre_est
base aerea               56269
canaveralejo             30434
compartir                35462
era - obrero             33129
ermita                   36823
estacion yumbo           24069
flora                    53841
pance                    31319
transitoria - navarro    19259
univalle                 48215
Name: concentracion, dtype: int64

In [22]:
print(df_cristian_dagma_2021_2025.groupby('nombre_est')['tipo_gas'].unique())

nombre_est
base aerea                    [o3, so2]
canaveralejo                      [so2]
compartir                          [o3]
era - obrero                       [o3]
ermita                            [so2]
estacion yumbo           [no2, o3, so2]
flora                         [so2, o3]
pance                              [o3]
transitoria - navarro         [so2, o3]
univalle                      [o3, no2]
Name: tipo_gas, dtype: object